// Re-export everything from the mastodon library for backwards compatibility
export {
  editAccount,
  getPeers,
  checkFollowing,
  getCurrentUser,
  unfollowUser,
  getAccount,
  getUsersPosts,
  getUsersFollowers,
  getFollowing,
  followUser,
  getInstanceInfo,
  initAuth,
  authToClient,
  registerAccount,
  getServers,
  isFollowingMe,
  muteUser,
  unmuteUser,
  blockUser,
  unblockUser,
  reportUser,
  type ReportOptions,
} from '../mastodon';
