// Re-export everything from the mastodon library for backwards compatibility
export {
  enrichPostsWithReplyContext,
  savePlace,
  getHomeTimeline,
  mixTimeline,
  addSomeInterestFinds,
  getPreviewTimeline,
  getTrendingLinks,
  resetLastPageID,
  getLastPlaceTimeline,
  getPaginatedHomeTimeline,
  getPublicTimeline,
  boostPost,
  reblogPost,
  getReplies,
  reply,
  mediaTimeline,
  searchTimeline,
  getHashtagTimeline,
  getAStatus,
  getTrendingStatuses,
} from '../mastodon';
