import { LitElement } from 'lit';
import '../components/timeline';
import '../components/timeline-item';
import '../components/md/md-skeleton';
import '../components/otter-drawer';
import '../components/md/md-button';
import '../components/md/md-badge';
import '../components/md/md-toolbar';
import '../components/md/md-menu';
import '../components/md/md-menu-item';
import '../components/md/md-dialog';
import '../components/md/md-switch';
import '../components/md/md-dropdown';
import '../components/md/md-tabs';
import '../components/md/md-tab';
import '../components/md/md-tab-panel';
import '../components/md/md-icon';
import '../components/md/md-icon-button';
import '../components/md/md-toast';
import { Post } from '../interfaces/Post';
export declare class AppHome extends LitElement {
    message: string;
    user: any | null;
    attachmentID: string | null;
    attachmentPreview: string | null;
    replies: any[];
    replyID: string | null;
    primary_color: string;
    instanceInfo: any | null;
    wellnessMode: boolean;
    dataSaverMode: boolean;
    sensitiveMode: boolean;
    attaching: boolean;
    summary: string;
    openTweet: Post | null;
    homeLoad: boolean;
    bookmarksLoaded: boolean;
    favoritesLoaded: boolean;
    notificationsLoaded: boolean;
    searchLoaded: boolean;
    appThemeLoaded: boolean;
    userTermsLoaded: boolean;
    rightClickLoaded: boolean;
    activeTab: string;
    static get styles(): import("lit").CSSResult[];
    constructor();
    firstUpdated(): Promise<void>;
    shareTarget(name: string): Promise<void>;
    handlePrimaryColor(color: string): void;
    share(): void;
    openNewDialog(): Promise<void>;
    publish(): Promise<void>;
    goToFollowers(): Promise<void>;
    goToFollowing(): Promise<void>;
    openSettingsDrawer(): Promise<void>;
    handleReplies(replies: any[], id: string): Promise<void>;
    replyToAStatus(): Promise<void>;
    openThemingDrawer(): Promise<void>;
    doFocusMode(): void;
    handleWellnessMode(check: boolean): Promise<void>;
    handleSensitiveContent(check: boolean): Promise<void>;
    handleDataSaverMode(mode: boolean): Promise<void>;
    removeImage(): void;
    openATab(name: string): void;
    shareMyProfile(): Promise<void>;
    viewMyProfile(): void;
    editMyProfile(): void;
    handleReload(): void;
    openBotDrawer(): void;
    showSummary($event: any): void;
    onMoveHandler(ev: any, dialog: any): void;
    handleOpenTweet(tweet: Post): Promise<void>;
    disconnectedCallback(): Promise<void>;
    reloadHome(): void;
    loadBookmarks(): Promise<void>;
    loadFavorites(): Promise<void>;
    loadNotifications(): Promise<void>;
    loadSearch(): Promise<void>;
    loadAppTheme(): Promise<void>;
    loadUserTerms(): Promise<void>;
    loadRightClick(): Promise<void>;
    handleTabChange(event: CustomEvent): Promise<void>;
    handleTranslating(_event: any): Promise<void>;
    render(): import("lit-html").TemplateResult<1>;
}
