import { LitElement } from 'lit';
import '../components/md/md-dialog';
import '../components/md/md-button';
import '../components/md/md-icon';
import '../components/md/md-skeleton-card';
import '../components/md/md-virtual-list';
import '../components/md/md-divider';
import '../components/timeline-item';
import '../components/search';
import '../components/md/md-select';
import '../components/md/md-option';
import { Post } from '../interfaces/Post';
export declare class Timeline extends LitElement {
    timeline: Post[];
    loadingData: boolean;
    lastScrollPosition: number;
    imgPreview: string | undefined;
    analyzeData: any | undefined;
    imageDesc: string | undefined;
    analyzeTweet: Post | null;
    isRefreshing: boolean;
    private _pullStartY;
    private _isPulling;
    private _pullDistance;
    private _threshold;
    private _hapticTriggered;
    timelineType: 'home' | 'public' | 'media' | 'for you' | 'home and some trending';
    static styles: import("lit").CSSResult[];
    firstUpdated(): void;
    private _setupPullToRefresh;
    private _getScrollContainer;
    _handleTouchStart(e: TouchEvent): void;
    _handleTouchMove(e: TouchEvent): void;
    _handleTouchEnd(): Promise<void>;
    connectedCallback(): Promise<void>;
    /** Handle load-more event from md-virtual-list */
    private _handleLoadMore;
    disconnectedCallback(): void;
    refreshTimeline(skipCache?: boolean): Promise<void>;
    loadMore(): Promise<void>;
    handleReplies(data: Array<Post>): void;
    showImage(imageURL: string): Promise<void>;
    showAnalyze(data: any, imageData: any, tweet: any): Promise<void>;
    changeTimelineType(type: 'home' | 'public' | 'media' | 'for you' | 'home and some trending'): Promise<void>;
    handleSummary($event: any): void;
    handleTranslating($event: any): void;
    handleOpen(tweet: any): void;
    render(): import("lit-html").TemplateResult<1>;
}
